### ISSUE TITLE
Error: "No member named 'forward_as_tuple' in namespace 'std::__1'" on iOS

### ISSUE THREAD

**Issue by zeman-88** [01org/tbb#107]
When using TBB on iOS, I get the following error:
![screen shot 2018-12-06 at 18 28 48](https://user-images.githubusercontent.com/45178918/49604072-d9cead00-f984-11e8-906f-bc7817f274b7.png)
![screen shot 2018-12-06 at 18 29 04](https://user-images.githubusercontent.com/45178918/49604079-dcc99d80-f984-11e8-8ec1-863a01676ce1.png)

These are the steps I follow to build for iOS:

```sh
make arch=arm64 target=ios tbb=release compiler=clang stdlib=libc++
```

I import and link against the produced `libtbb.dylib` and `libtbbmalloc.dylib` in my Objective-C project in XCode as such:
![screen shot 2018-12-06 at 18 25 47](https://user-images.githubusercontent.com/45178918/49603943-88262280-f984-11e8-84bf-bebb2560acae.png)
![screen shot 2018-12-06 at 18 26 16](https://user-images.githubusercontent.com/45178918/49603950-8e1c0380-f984-11e8-91c4-097326d65396.png)
![screen shot 2018-12-06 at 18 26 39](https://user-images.githubusercontent.com/45178918/49603958-91af8a80-f984-11e8-9a98-803c7a5debe3.png)

And finally include the main header in my `.mm` file in XCode:
![screen shot 2018-12-06 at 18 27 59](https://user-images.githubusercontent.com/45178918/49604013-b3107680-f984-11e8-8003-0ea8729e9d06.png)

I have googled for the error but haven't found an explanation yet. Is this a known bug, and if so, how do I fix it?
I am using XCode Version 10.1 (10B61) on MacOS High Sierra 10.13.6 (17G65).

**Comment by akukanov** [comment]
Do I understand it correct that
- you have successfully built TBB binaries for iOS, but are not able to compile your own code?
- your code is Objective-C, not C++?
- you have just included the TBB header but did not yet use any API?

**Comment by zeman-88** [comment]
@akukanov 
1. Yes; I built them with the command above. Here are the contents of the folder `tbb-2019_U3/build/macos_arm64_clang_cc10.0.0_ios12.1_release`:
```sh
arena.d				concurrent_vector.o		large_objects.d			queuing_mutex.d			spin_rw_mutex.o			tbb_misc_ex.o
arena.o				concurrent_vector_v2.d		large_objects.o			queuing_mutex.o			spin_rw_mutex_v2.d		tbb_statistics.d
backend.d			concurrent_vector_v2.o		libtbb.dylib			queuing_rw_mutex.d		spin_rw_mutex_v2.o		tbb_statistics.o
backend.o			condition_variable.d		libtbbmalloc.dylib		queuing_rw_mutex.o		task.d				tbb_thread.d
backref.d			condition_variable.o		libtbbmalloc_proxy.dylib	reader_writer_lock.d		task.o				tbb_thread.o
backref.o			critical_section.d		market.d			reader_writer_lock.o		task_group_context.d		tbbmalloc.d
cache_aligned_allocator.d	critical_section.o		market.o			recursive_mutex.d		task_group_context.o		tbbmalloc.def
cache_aligned_allocator.o	dynamic_link.d			mutex.d				recursive_mutex.o		task_v2.d			tbbmalloc.o
concurrent_hash_map.d		dynamic_link.o			mutex.o				rml_tbb.d			task_v2.o			tbbvars.csh
concurrent_hash_map.o		frontend.d			observer_proxy.d		rml_tbb.o			tbb.def				tbbvars.sh
concurrent_monitor.d		frontend.o			observer_proxy.o		scheduler.d			tbb_function_replacement.d	version_string.ver
concurrent_monitor.o		governor.d			pipeline.d			scheduler.o			tbb_function_replacement.o	x86_rtm_rw_mutex.d
concurrent_queue.d		governor.o			pipeline.o			semaphore.d			tbb_main.d			x86_rtm_rw_mutex.o
concurrent_queue.o		itt_notify.d			private_server.d		semaphore.o			tbb_main.o
concurrent_queue_v2.d		itt_notify.o			private_server.o		spin_mutex.d			tbb_misc.d
concurrent_queue_v2.o		itt_notify_malloc.d		proxy.d				spin_mutex.o			tbb_misc.o
concurrent_vector.d		itt_notify_malloc.o		proxy.o				spin_rw_mutex.d			tbb_misc_ex.d
```

2. Yes; my project is Objective-C based, and the implementation file in which I include `<tbb/tbb.h>` is an **Objective-C++ file**, as it has the `.mm` ending.

3. Correct; I have simply included `<tbb/tbb.h>` at the top of my `myImplFile.mm` file and have not made any calls to the API.

For more context, here is one of the places it says the error comes from:
![screen shot 2018-12-06 at 19 17 32](https://user-images.githubusercontent.com/45178918/49606576-ac393200-f98b-11e8-93de-868594e24b2e.png)

**Comment by zeman-88** [comment]
@akukanov 

For even more context, here how I could reproduce it with a minimal example:

1. Create a new CocoaTouch Framework, Objective-C based, with XCode
2. Once that's open and created, press CTRL+N to create a new file and choose C++; give it a test name
3. Download TBB 2019_U3 and build it with: `make arch=arm64 target=ios tbb=release compiler=clang stdlib=libc++`
4. Setup the project settings in Build Settings as I have shown in the previous screenshots; i.e. by setting the header search paths to the `include`, `src`, etc directories of the TBB folder and by linking to the newly created `libtbb.dylib` under **Linked Libraries and Frameworks**.
5. Hit the build button

**Comment by akukanov** [comment]
Honestly, so far it does not look like a TBB issue. `forward_as_tuple` is a [standard function](https://en.cppreference.com/w/cpp/utility/tuple/forward_as_tuple). And [TBB does not even use this function](https://github.com/01org/tbb/search?q=forward_as_tuple&unscoped_q=forward_as_tuple).

Do you know if Objective-C++ support C++11 features? What if instead of `<tbb/tbb.h>` you directly include some standard C++ header, e.g. `<tuple>` or `<functional>`?

**Comment by zeman-88** [comment]
@akukanov yes it does, and in fact if I remove the `tbb/include` folder from the headers search path, I can compile and can compile even C++11 code such as this:

The C++ file:
![screen shot 2018-12-06 at 19 40 22](https://user-images.githubusercontent.com/45178918/49607793-eeb03e00-f98e-11e8-9595-137947ec4a86.png)

The Objective-C++ file in the same project:
![screen shot 2018-12-06 at 19 40 16](https://user-images.githubusercontent.com/45178918/49607804-f243c500-f98e-11e8-930a-b81cb1014f94.png)

These both compile ok if I remove the search for headers path to `tbb/include` as I explained above.

**Comment by akukanov** [comment]
OK, we will investigate.

Unrelated to the issue, I'd recomment you to keep only `tbb-2019_U3/include` in your header paths, and remove `src` and its subdirectories which are not necessary to use TBB.

**Comment by zeman-88** [comment]
@akukanov thank you. Thanks for the tip, and in fact in the simple and reproducible example I gave above, I only added `tbb-2019_U3/include` to the header paths, and the error still reproduced.

**Comment by akukanov** [comment]
@zeman-88, can you please provide the command line which Xcode uses to compile your Objective-C++ file?

**Comment by zeman-88** [comment]
I managed to find out it was a problem on my side.

**Comment by wizecare** [comment]
Zeman-88, do you recall how you fixed the problem?

**Comment by eshorr** [comment]
Do you recall how fixed the problem? Zeman-88?

**Comment by thomas-graphopti** [comment]
@zeman-88 hi, zeman; do you mind share your solution to this problem?

**Comment by thomas-graphopti** [comment]
@eshorr  hi, eshorr; do you solve this problem? if so, could you share your solution? thx.
