### ISSUE TITLE
Add support for building with CC and CXX specified as absolute paths

### ISSUE THREAD

**Issue by martymac** [01org/tbb#11]
Hi,

Trying to build tbb with CC and CXX specified as absolute paths lead to errors, see that PR on FreeBSD :

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=215656

Could you have a look at the following patch and maybe integrate it upstream ? :

https://svnweb.freebsd.org/ports/head/devel/tbb/files/patch-common.inc?view=co

Thanks !

**Comment by alexey-katranov** [comment]
Hi,

As I understand, you want to build the Intel TBB library using full path in the `compiler` variable. Do you use something like `compiler = $(CC)`? In the patch the `compiler` variable is stripped to use only the file name. Is it expected that the result will be `clang38.inc`? The Intel TBB package does not have such file and you need to provide it (or create a link to clang.inc). I am asking to understand your usage model to implement the right solution.

Regards,
Alex

**Comment by martymac** [comment]
Hi Alexey,

Yes, the patch will use only the file name and getting e.g. clang38.inc is something intended. Our FreeBSD port will create that file on the file using the clang.inc file as a template. That behaviour is used to support multiple versions of the compiler (of two families : gcc and clang). You can have a look at the port's Makefile (post-extract target) for more details :

https://svnweb.freebsd.org/ports/head/devel/tbb/Makefile?revision=430719&view=co

The proposed patch will not break current builds but it will help building in situations where users set a full path for CC.

**Comment by alexey-katranov** [comment]
Could you try Intel TBB 2017 Update 5, please? It should fix the issue.

**Comment by martymac** [comment]
Yes it does, thanks Alexey!
