### ISSUE TITLE
include\tbb\concurrent_unordered_map.h(48): error C2143: syntax error: missing ',' before '<'

### ISSUE THREAD

**Issue by ttnghia** [01org/tbb#13]
**Problem:** <long path>\include\tbb\concurrent_unordered_map.h(48): error C2143: syntax error: missing ',' before '<'

<long path>\include\tbb\concurrent_unordered_map.h(61): note: see reference to class template instantiation 'tbb::interface5::concurrent_unordered_map_traits<Key,T,Hash_compare,Allocator,Allow_multimapping>::value_compare' being compiled

<long path>\include\tbb\concurrent_unordered_map.h(70): note: see reference to class template instantiation 'tbb::interface5::concurrent_unordered_map_traits<Key,T,Hash_compare,Allocator,Allow_multimapping>' being compiled

**When:** A _parallel_for_ code compiling on VS2017 with compiler parameter /std:c++latest. Compiling with /std:c++14 does not produce the issue.

**Comment by xC0DEB10C** [comment]
std::binary_function was removed from C++17. TBB needs to update it's source code to support building against C++17. All you can do write now is not use "concurrent_unordered_map.h". For example, create a custom "tbb.h" that doesn't include it.

**Comment by tbbdev** [comment]
Hello, ttnghia.
Problem that you reported was fixed in Intel TBB 2017 U6:
https://github.com/01org/tbb/blob/tbb_2017/CHANGES#L20

Can we close this thread?

**Comment by ttnghia** [comment]
Sure. Thank you very much :)
