### ISSUE TITLE
Support for VS 2017

### ISSUE THREAD

**Issue by adityaatluri** [01org/tbb#14]
Hi,
Will there be support for visual studio 2017 community edition?

**Comment by alexey-katranov** [comment]
According to the latest changes (Intel TBB 2017 Update 5) "Microsoft* Visual Studio* 2017" is supported. I suppose it does not depend on a specific edition. Do you observe some issues with the community edition?

**Comment by Chandra03ram** [comment]
I don't think (Intel TBB 2017 Update 5) is supported for visual studio 2017. I'm using visual studio 2017 to build my project, where i need to use tbb, but there is no version of TBB that supports, visual studio 2017.
Generally, lib folder in the TBB should have vc15 folder to support vs2017. But, it is not provided in the TBB, thus there is no support of TBB for vs2017.

**Comment by akukanov** [comment]
The [documentation](https://www.threadingbuildingblocks.org/docs/help/tbb_userguide/Windows_OS_ug.html) specifies that the same binaries (vc14) are used for both VS 2015 and VS 2017.
