### ISSUE TITLE
inpreciese documentation of task_group::wait()

### ISSUE THREAD

**Issue by anton-potapov** [01org/tbb#19]
From here  https://www.threadingbuildingblocks.org/docs/help/reference/task_groups/task_group_cls/task_group_cls_members.html : 

Member | Description
------------ | -------------
  **task_group_status** wait()  |  Wait for all tasks in the group to complete or be canceled. Returns: **True** if this task group is canceling its tasks. 

Return type in the description (`bool`) conflict with one in signature (`task_group_status`)

**Comment by PovelikinRostislav** [comment]
Hi, anton-potapov.

This issue was fixed.

Could you please confirm it?

**Comment by anton-potapov** [comment]
confirmed :)
