### ISSUE TITLE
C++11 support in Clang with libstdc++.

### ISSUE THREAD

**Issue by p0lszewski** [01org/tbb#22]
The following program:
```
//////////////
// main.cpp //
//////////////
#include "tbb/concurrent_unordered_set.h"

struct S
{
  int i;
  double f;

  S(int i, double f)
  : i(i)
  , f(f)
  {
  }

  bool operator==(const S &other) const
  {
    return i == other.i && f == other.f;
  }
};

namespace tbb
{

template<>
struct tbb_hash<S>
{
  size_t operator()(const S & self) const
  {
    return std::hash<int>{}(self.i) ^ std::hash<double>{}(self.f);
  }
};
}

int main()
{
  tbb::concurrent_unordered_set<MyStruct> s;
  s.emplace(0, 0.0);
}
```
Cannot be compiled using `clang++ -std=c++11` on my x86-64 Linux Ubuntu 16.04 with the following error:
```
main.cpp:39:5: error: no member named 'emplace' in
      'tbb::interface5::concurrent_unordered_set<S, tbb::tbb_hash<S>,
      std::equal_to<S>, tbb::tbb_allocator<S> >'
  s.emplace(0, 0.0);
```
The problem persists across compiler versions (I tested the official Clang 4.0 binaries from the LLVM site and Clang 3.8 binaries from the repositories) and library versions (I tested the official 4.4-2017/06/04 and the 4.4-2015/11/15 present in the repositories).

It seems to me that some C++11 features are not correctly checked for when it comes to Clang with libstdc++. For instance, at `tbb/tbb_config.h:151`:
```
#define __TBB_CPP11_RVALUE_REF_PRESENT                  (__has_feature(__cxx_rvalue_references__) && (_LIBCPP_VERSION || __TBB_GLIBCXX_VERSION >= 40500))
```
The problem with this is that `__TBB_GLIBCXX_VERSION` is not the actual libstdc++'s version, it defaults to GCC compiler version. The problem is that Clang is only compatible with GCC-4.2.1. This means that `__TBB_GLIBCXX_VERSION` is stuck at `40201`, even though the actual version of libstdc++ that clang uses may be high enough to enable these features. There doesn't seem to be any easy/correct way to fix this, because AFAIK there are no macros to check libstdc++'s version directly (there's `__GLIBCXX__`, but that's just the timestamp of when the library was built). The Boost people were having a [similar problem](https://svn.boost.org/trac10/ticket/7473) until somebody came up with a [patch](https://github.com/boostorg/config/commit/b36566fe04a89103b7ef5569c03e3a26eb77af36) that tries to determine libstdc++'s version based on `#include`'s it offers. Could this approach be feasible for TBB?

**Comment by tbbdev** [comment]
Hello, Piotr.
This is a known issue:  "If you compile with Clang and the GNU libstdc++ library, Intel TBB headers cannot correctly detect availability of C++11 features. To overcome the issue, define the TBB_USE_GLIBCXX_VERSION macro to the proper version of libstdc++ before including any Intel TBB header file."
https://www.threadingbuildingblocks.org/docs/help/reference/appendices/known_issues/linux_os.html

**Comment by det** [comment]
`_GLIBCXX_RELEASE` can be used since libstdc++ 7 to determine the major version. I suggest defining `__TBB_GLIBCXX_VERSION` as `(_GLIBCXX_RELEASE*1000)` when compiling TBB with clang and libstdc++ and  `_GLIBCXX_RELEASE`  is defined.

```Since GCC 7, incremental bumping of a library pre-defined macro, _GLIBCXX_RELEASE. This macro is defined to the GCC major version that the libstdc++ headers belong to, as an integer constant. When compiling with GCC it has the same value as GCC's pre-defined macro __GNUC__. This macro can be used when libstdc++ is used with a non-GNU compiler where __GNUC__ is not defined, or has a different value that doesn't correspond to the libstdc++ version.```

**Comment by akukanov** [comment]
@det, thank you for the suggestion. It will be added into a future update.
