### ISSUE TITLE
Debug TBB build for ARM (arm-linux-gnueabihf-g++-5.2) failed

### ISSUE THREAD

**Issue by Semen52** [01org/tbb#28]
TBB  version: Commit: eb6336a [eb6336a] (Committing Intel(R) TBB 2017 Update 7)

> tbb/_build/tbb-tbb_2017/include/tbb/tbb_machine.h: In function 'intptr_t __TBB_Log2(uintptr_t)':
> tbb/_build/tbb-tbb_2017/include/tbb/tbb_machine.h:862:61: error: 'tmp_' may be used uninitialized in this function [-Werror=maybe-uninitialized]
>      if( sizeof(x)>4 && (tmp_ = ((uint64_t)x)>>32) ) { x=tmp_; result += 32; }

> arm-linux-gnueabihf-g++ -o pipeline.o -c -MMD -DTBB_USE_DEBUG  -g -O0 -DUSE_PTHREAD -Wa,-mimplicit-it=thumb  -fPIC  -D__TBB_BUILD=1 -Wall -Wno-parentheses -Wno-non-virtual-dtor -Wall -Wno-reorder -Wno-unknown-pragmas -MMD -fPIC -std=c++98 -Werror -ggdb -fno-inline -fno-omit-frame-pointer -D__TBB_DYNAMIC_LOAD_ENABLED=0 -D__TBB_SOURCE_DIRECTLY_INCLUDED=1

**tbb_machine.h:**
inline intptr_t __TBB_Log2( uintptr_t x ) {
    if( x==0 ) return -1;
    intptr_t result = 0;

#if !defined(_M_ARM)
    uintptr_t tmp_;
    if( sizeof(x)>4 && (tmp_ = ((uint64_t)x)>>32) ) { x=tmp_; result += 32; }
#endif
    if( uintptr_t tmp = x>>16 ) { x=tmp; result += 16; }
    if( uintptr_t tmp = x>>8 )  { x=tmp; result += 8; }
    if( uintptr_t tmp = x>>4 )  { x=tmp; result += 4; }
    if( uintptr_t tmp = x>>2 )  { x=tmp; result += 2; }

    return (x&2)? result+1: result;
}

Is it applicable only for _M_ARM? or for __arm__ too?

**Comment by ntfshard** [comment]
Hello

It's a false positive warning; Variable tmp\_ will be initialized in the right side of the logical operator.
[tbb_machine.h#L862](https://github.com/01org/tbb/blob/tbb_2017/include/tbb/tbb_machine.h#L862)

**Comment by Semen52** [comment]
Hi,

Good. How I can suppress this error? Exclude -Werror flag isn't right way ...

**Comment by ntfshard** [comment]
I guess you could try to initialize this variable `uintptr_t tmp=0;` or disable "maybe-uninitialized" warning.

**Comment by ashokbugude** [comment]
@Semen52 Can I please know the steps you have followed to build for arm (arm-linux-gnueabihf-g++-5.2)
Thanks

**Comment by Semen52** [comment]
@ashokbugude On the ARM platform: make extra_inc=big_iron.inc tbb
For cross-compile: edit Makefiles and add arch=armv7 or rch=aarch64

**Comment by ashokbugude** [comment]
Thanks able to build it
