### ISSUE TITLE
TBB releases are not persistent

### ISSUE THREAD

**Issue by Lastique** [01org/tbb#30]
I'm working on an environment for building packages of third party libraries used by our project, and TBB is one of those libraries. We download third party source code from the upstream (like GitHub in case of TBB) and build it ourselves. One part of the job is to ensure that whatever is downloaded is genuine, so we verify the SHA-256 checksum of the downloaded source code.

With TBB we discovered that the source code of a shipped release is not persistent and can change without any notification. This was the case with 2017u7, which was first released on 2017-06-04 (the .tar.gz archive SHA-256 was 755b7dfaf018f5d8ae3bf2e8cfa0fa4672372548e8cc043ed1eb5b22a9bf5b72) and currently the tag corresponds to a commit on 2017-06-07 (SHA-256: 78ad6ec9dd492b9dcc4753938b06716f7458506084adc138ced09aa0aa609b6b).

This is a big problem for us because we cannot know what code is the 2017u7 version and we cannot be sure that any of the source releases is genuine. Please, change your release practices.

**Comment by ntfshard** [comment]
Hello
As far as I understand you told about "Source code (zip)" and "Source code (tar.gz)" on a https://github.com/01org/tbb/releases page. As far as I know this files are generates by github by user request and can't be managed directly (they tied to a tag)

**Comment by Lastique** [comment]
Yes, that's the files I'm referring to. What I'm saying is that I suspect that git history was rewritten and the same git tag now refers to a different commit, and that caused the files to change.

**Comment by tbbdev** [comment]
Hi, Lastique.
Yes, last time git history was rewritten and it was made by mistake.
Thank you for reporting this problem. We understand that persistent releases are important and we will do our best to avoid problem like this in the future.
