### ISSUE TITLE
CMake TBBBuild does not support MinGW-w64 mingw32-make

### ISSUE THREAD

**Issue by sjthebat** [01org/tbb#32]
The build fails with the message "Intel TBB can not be built: required make-tool (gmake) was not found".

TDM-GCC comes with mingw32-make, instead of gmake.

**Comment by tbbdev** [comment]
Hello, sjthebat.
We don't support mingw32-make and recommend you install gmake on your system.
MinGW is supported by Intel TBB open source community and if you want to improve this support you can contribute into project through: https://www.threadingbuildingblocks.org/submit-contribution or via pull request.

**Comment by ntfshard** [comment]
Hello
IMHO you can try to copy&rename mingw32-make to gmake. It should help.

**Comment by sjthebat** [comment]
@tbbdev It's good to know.
@ntfshard Renaming mingw32-make to gmake moved the process one step further. But there are other road blocks. Thanks!
