### ISSUE TITLE
threadingbuildingblocks.org website spells "repository" as "reposiotry"

### ISSUE THREAD

**Issue by Mankarse** [01org/tbb#34]
The news section of https://www.threadingbuildingblocks.org/news-archive includes the following text for each recent release:

    Files are available on the release page of the Github reposiotry.

"reposiotry" is not a word. This should be fixed to read:

    Files are available on the release page of the Github repository.

**Comment by tbbdev** [comment]
Hello, Mankarse.
This typo was fixed. Thank you for reporting it,
