### ISSUE TITLE
Calling .find(const_accessor, _) on a concurrent_hash_map during iteration causes jumping iterator.

### ISSUE THREAD

**Issue by pnappa** [01org/tbb#45]
For reasons unbeknownst to me, interacting with the concurrent_hash_map with a const_accessor during iteration, appears to cause the iterator to skip and repeat certain elements.

Minimal working example (compiled with g++ 7.2.0):

```c++
#include <iostream>
#include <memory>
#include <tbb/concurrent_hash_map.h>

int main() {
    typedef tbb::concurrent_hash_map<size_t, size_t> mappi;
    mappi x;

    constexpr size_t kkk = 1000000;
    for (size_t i = 0; i < kkk; ++i) {
        typename mappi::accessor a;
        x.insert(a, i);
        a->second = i;
    }

    // count that is spuriously too much
    size_t count = 0;
    for (auto& o : x) {
        typename mappi::const_accessor a;
        x.find(a, o.first);
        ++count;
    }

    std::cout << x.size() << std::endl; // outputs 1000000
    std::cout << count << std::endl; // outputs 1262143 (!!) 

    // regular correct count
    count = 0;
    for (auto& o : x) {
        ++count;
    }

    std::cout << x.size() << std::endl; // outputs 1000000
    std::cout << count << std::endl; // outputs 1000000

    return 0;
}
```

Produces output as described by the comments.

From what I can tell from the documentation, this is not correct behaviour.

**Comment by anton-malakhov** [comment]
Documentation says here [1](https://www.threadingbuildingblocks.org/docs/help/reference/containers_overview/concurrent_hash_map_cls/iterators_hash_map_cls.html) that `Do not call concurrent operations, including count and find while iterating the table. Use concurrent_unordered_map if concurrent traversal and insertion are required.` and here [2](https://www.threadingbuildingblocks.org/docs/help/reference/containers_overview/concurrent_hash_map_cls/concurrent_operations_hash.html) that `The concurrent operations (count, find, insert, and erase) invalidate any iterators pointing into the affected instance even with a const qualifier. It is unsafe to use these operations concurrently with any other operation. An exception to this rule is that count and find do not invalidate iterators if no insertions or erasures have occurred after the most recent call to method rehash.`

**Comment by pnappa** [comment]
Ah, seems to be my misinterpretation of `concurrent'. Thanks for clearing this up, and providing a quick and easy solution too - rehashing after the insertion block has occurred produces the correct result.
