### ISSUE TITLE
2018_U3 retagged?

### ISSUE THREAD

**Issue by commitay** [01org/tbb#49]
https://github.com/01org/tbb/archive/2018_U3.tar.gz

On the 31/03 the `sha256` was `a0be619c741ee399de740ee7192c41a92fbbc7a8f3bda3032d6d6167e13f9dac`

Currently the `sha256` is `23793c8645480148e9559df96b386b780f92194c80120acce79fcdaae0d81f45`

We need to confirm that the checksum change is legitimate before we can update the Homebrew formula.

**Comment by tbbdev** [comment]
Yes, the release 2018 U3 has been retagged to include [updates](https://github.com/01org/tbb/commit/633b01ad27e012e1dc4e392c3230250d1f4967a4) for [conda-forge integration](https://github.com/conda-forge/tbb-feedstock/pull/21).

**Comment by anton-malakhov** [comment]
@commitay Speaking of the Homebrew distribution, do you guys want to reuse the build/build.py script, which implements the missing `make install` stage for the library? It was designed to enable package splitting into `tbb`, `tbb-devel`, and `tbb4py` parts and also enable convergence between tbb packages across all the distributions & vendors. So the content/structure of the packages will be the same everywhere
