### ISSUE TITLE
ARMv8 support patch submission

### ISSUE THREAD

**Issue by siddhesh** [01org/tbb#51]
Sorry if this is not the right forum to ask this question, but it was either this forum or the Intel developer forum[1] and both seemed similarly ill-fitted for the purpose.

I had submitted a patch to enable armv8 support for libtbb with an optimization for __TBB_Pause using the documented instructions[2].  I was told that I'll get feedback in 2 business days but it has been 12 days now.  Can someone from the dev team please guide me on how to get feedback and/or continue contributing to the library?

Thanks,
Siddhesh

[1] https://software.intel.com/en-us/forums/intel-threading-building-blocks
[2] https://www.threadingbuildingblocks.org/submit-contribution

**Comment by alexey-katranov** [comment]
@siddhesh , thank you for contribution and sorry for a long responce.

We have considered your patch and your idea is worth contributing. However, it looks like your idea can be applied for armv7a as well (as it also has the `yield` instruction), so we would prefer to have all arm-related code in one file. In addition, it will be easier to extend for further arm generations. Could you merge the newly added file into `gcc_armv7.h` (perhaps renamed to `gcc_arm.h`) using `gcc_generic.h` for all generations beside armv7a (for which you keep the current one) and implementing `__TBB_Pause` with your approach?

I would also recommend to open a pull request on github with your patch to simplify the communication process (we can add comments bound to the code).

**Comment by siddhesh** [comment]
Thanks for your feedback.  I'll rework my patch and send it to you shortly.  A PR on github actually works much better for me too, I just assumed y'all preferred the traditional route since that's the documented method on the website :)

I'll close this issue and open a PR when I have the patch. Thanks!
