### ISSUE TITLE
threadingbuildingblocks.org SSL certificate expired

### ISSUE THREAD

**Issue by JavierCVilla** [01org/tbb#55]
Ey guys, it seems the SSL certificate of the website expired last night.

**Comment by tbbdev** [comment]
Hi Javier, thank you! The problem was fixed. Could you check it from your side and close the issue?

**Comment by JavierCVilla** [comment]
Hi @tbbdev , yes it works! indeed since yesterday afternoon. Closing.
Thanks! :)
