### ISSUE TITLE
cannot open 'tbb.dll' 

### ISSUE THREAD

**Issue by KleinGeard** [01org/tbb#80]
Here's the error message I'm getting: 

> The program can't start because tbb.dll is missing from your computer. Try reinstalling the program to fix this problem.

I'm using Visual Studio 2017 community

I've added the include folder to the project just fine and added the tbb.lib from 'tbb2018_20180618oss\lib\ia32\vc14' to the linker.

What am I doing wrong?

Here's the code I'm trying to run

```
// TBBPractice2.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include "tbb/task_scheduler_init.h"
using namespace tbb;

int main()
{
	task_scheduler_init init;

	printf("hello");

    return 0;
}
```

**Comment by ntfshard** [comment]
Hello
You should add a path to the `tbb.dll` into the PATH environmental variable(in your console or user profile) OR copy `tbb.dll` in the same folder with your executable file.

**Comment by KleinGeard** [comment]
Thank You!
