### ISSUE TITLE
task_scheduler_init warning message

### ISSUE THREAD

**Issue by jrmadsen** [01org/tbb#81]
I had an interesting minor issue that I resolved but I feel there should be a warning message emitted.

- A "run manager" had a `tbb::task_group` member variable and another member variable class instance that instantiated the `tbb::task_scheduler_init` when the number of threads was specified
- The creation of the `tbb::task_group` implicitly created a `tbb::task_scheduler_init` instance during the construction of the "run manager" and assigned that instance as the thread-local static singleton for this thread
- Thus, when the class member variable was created later, which created a `tbb::task_scheduler_init` instance on the same thread, this had no effect
  - I understand why this happened but there is only supposed to be one scheduler initialization per thread so always having a check like `if(governor::theTLS.get()) { std::cerr << "Scheduler already instantiated for thread " << std::this_thread::get_id() << std::endl; }` would cause essentially zero overhead

**Comment by alexey-katranov** [comment]
While only one task scheduler initialization per thread is possible, TBB allows more than only one reference to an internal representation. It is a supported usage model when multiple `tbb::task_scheduler_init` are created on the same thread at the same time.
If you want to check if the task scheduler initialization is done for the current thread, you can use [`this_task_arena::current_thread_index`](https://software.intel.com/en-us/node/506359).

**Comment by akukanov** [comment]
Nowadays, you hardly ever need `tbb::task_scheduler_init` at all. Thread stack size should better be set with `tbb::global_control`; concurrency is better managed by `tbb::global_control` and `tbb::task_arena`, and if you do not care of either, there is implicit scheduler initialization.

That said, I agree it's not so good that the `tbb::task_group` ctor does implicit initialization. We will see if this can be improved.
