### ISSUE TITLE
s390x still considered as 32-bit arch

### ISSUE THREAD

**Issue by sharkcz** [01org/tbb#9]
Seems that even with the recent change https://github.com/01org/tbb/blob/tbb_2017/build/linux.inc#L102 the s390x architecture is still considered as 32-bit (not understood as 64-bit). We have used http://pkgs.fedoraproject.org/cgit/rpms/tbb.git/tree/tbb-2017-64bit.patch?id=487f57941428c310003d531c3bad6ed22075824a to fix that.

The Fedora s390x build of tbb is available at https://s390.koji.fedoraproject.org/koji/buildinfo?buildID=444404 and if you inspect the build.log in the "Build logs" link, you will see that lin32-tbb-export.def is used, which is wrong.

**Comment by tbbdev** [comment]
Hi, sharkcz.
Thank you for reporting this problem. 
We will notify you when it will be resolved.

**Comment by tbbdev** [comment]
Hi, sharkcz.
This issue was fixed in Intel TBB 2017 U5 release.
Could you please confirm it?

**Comment by sharkcz** [comment]
yes, it is, lin64-tbb-export.def is used for creating tbb.def
