### ISSUE TITLE
macOS 10.14 Mojave support

### ISSUE THREAD

**Issue by raynexuslin** [01org/tbb#96]
It seems that current versions do not support the latest macOS.

**Comment by nik-ponomarev** [comment]
@raynexuslin, could you, please, describe the problem more detailed?

**Comment by raynexuslin** [comment]
I'm so sorry. This was a mistake on my side. Sorry for any inconvenience caused. TBB is working properly on macOS Mojave.

**Comment by raynexuslin** [comment]
Actually, I meant to say that non of the release versions on Github release notes indicate support for macOS 10.14. However, I later tried installing TBB via Homebrew and it was a success. It runs properly as well. Sorry again for opening a random issue. There is no problem with TBB.
