### ISSUE TITLE
use concurrent_queue generate cpu 100%

### ISSUE THREAD

**Issue by yuinm** [01org/tbb#97]
hi , I use concurrent_queue generate cpu 100% , and then I try to solve by add micro queue size from 8 to 32 ,then run well at online server , but yesterday we do stress Test , the problem happen again .
I want to try  reduce "push"  frequency  by thread local queue ,but the item order is error .
What can I do ,about this .
my machine have 16 core , launch 64 thread do push ,  and concurrent_queue`s  inner queue  change to 32
what can i do about this .
thanks 
Looking forward to your reply.

**Comment by alexey-katranov** [comment]
Could you describe the desired behavior, please? As I understand, the algorithm performs multiple pushes from multiple threads. Since the queue has "unlimited" size, the threads will continue perform the push operation until they have something to push. Therefore, 100% utilization is expected in that case.

**Comment by yuinm** [comment]
> Could you describe the desired behavior, please? As I understand, the algorithm performs multiple pushes from multiple threads. Since the queue has "unlimited" size, the threads will continue perform the push operation until they have something to push. Therefore, 100% utilization is expected in that case.

Yes , has many thread do push operation , but too many thread block in spin lock, because they should wait theirs ticket , so when many thread trap in  the spin lock , cpu will 100% . 
now I have to increase the micro queue count  , retard clash .

**Comment by alexey-katranov** [comment]
What type of elements stored inside the concurrent queue? Is it trivial (e.g. `int`) or something complex (e.g. `std::vector`)?

**Comment by yuinm** [comment]
it is int*.
